# Generated by Django 4.1 on 2022-08-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminlogin',
            new_name='Login',
        ),
    ]
