# Generated by Django 4.1 on 2022-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='age',
        ),
        migrations.AddField(
            model_name='registration',
            name='Id_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='nationality',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
