# Generated by Django 4.1 on 2022-08-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_registration_age_registration_id_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinics', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
