# Generated by Django 4.1 on 2022-08-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_clinics_clinics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clinics',
            new_name='Clinic',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='clinics',
            new_name='clinic',
        ),
    ]
